### ISSUE TITLE
Code 4 feedback

### ISSUE THREAD

**Issue by bigfatnoob** [tnkteja/fss16ntadiko#3]
Your code might need improvement. Ideally after 1000 gens, your solution should be close to x=1. Your best solution is at x=-93047. Run it multiple times and see if it ends up close to this or check if there is a bug in your code. If you have trouble understanding SA, come talk to me.

**Comment by tnkteja** [comment]
I think the code is good for the maximizing problem.  For minimizing problem, there is something missig, emax is not appropriate and the comparision, which are fixed.

**Comment by bigfatnoob** [comment]
The problem is a minimizing one so you would need to work on it appropriately.
